#Edited by Vince Stevens - 18 Feb 2021

#This file sets some of the basic properties for the website, 
#includeing information in the header, footer, etc.

#Jekyll Theme for the website
theme: jekyll-theme-cayman
